### ISSUE TITLE
File exist error when using the save() function

### ISSUE THREAD

**Issue by Siriu5J** [aVadim483/fast-excel-templator#4]
I am attempting to fill out an Excel form using the templator. However, whenever I attempt to save the file (even without doing any editing, the fatal error below will still show up).

```
[14-Mar-2024 07:04:21 UTC] PHP Fatal error:  Uncaught avadim\FastExcelWriter\Exceptions\Exception: File "/var/www/html/wordpress/wp-content/plugins/judges-form-auto-generate/files/tmp/output.xlsx" already exists in /var/www/html/wordpress/wp-content/plugins/judges-form-auto-generate/lib/composer/vendor/avadim/fast-excel-writer/src/FastExcelWriter/Exceptions/Exception.php:20
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/judges-form-auto-generate/lib/composer/vendor/avadim/fast-excel-writer/src/FastExcelWriter/Writer.php(350): avadim\FastExcelWriter\Exceptions\Exception::throwNew()
#1 /var/www/html/wordpress/wp-content/plugins/judges-form-auto-generate/lib/composer/vendor/avadim/fast-excel-writer/src/FastExcelWriter/Excel.php(203): avadim\FastExcelWriter\Writer->saveToFile()
#2 [internal function]: avadim\FastExcelWriter\Excel->__destruct()
#3 {main}
  thrown in /var/www/html/wordpress/wp-content/plugins/judges-form-auto-generate/lib/composer/vendor/avadim/fast-excel-writer/src/FastExcelWriter/Exceptions/Exception.php on line 20
```

I noticed that the file is still written when using the template() function. Maybe that is why the Writer is not liking it.

**Comment by Siriu5J** [comment]
By the way, the file still gets saved with that error.

**Comment by aVadim483** [comment]
fixed
